- name: Deploy WordPress site
  become: yes
  hosts: all

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Docker (compose included)
      ansible.builtin.shell: docker ps || curl -fsSL https://get.docker.com | sh
      args:
        chdir: /tmp/

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Destroy old deploy
      shell: docker compose down --rmi all -v
      args:
        chdir: /tmp/docker
      ignore_errors: true

    - name: Copy docker files
      copy:
        src: ./docker
        dest: /tmp

    - name: Generate .env file
      command: sh /tmp/docker/generate_env_and_domain.sh
      args:
        chdir: /tmp/docker
      environment:
        DOMAIN_NAME: "{{ ansible_host }}"
      register: env_gen

    - debug: var=env_gen.stdout_lines

    - name: Launch Docker Compose
      command: docker compose up -d
      args:
        chdir: /tmp/docker
